{ name = "my-project"
, dependencies =
  [ "arrays"
  , "console"
  , "datetime"
  , "effect"
  , "either"
  , "exceptions"
  , "express"
  , "foldable-traversable"
  , "foreign"
  , "lists"
  , "maybe"
  , "monad-loops"
  , "node-buffer"
  , "node-child-process"
  , "node-fs"
  , "node-path"
  , "open-foreign-generic"
  , "ordered-collections"
  , "posix-types"
  , "prelude"
  , "refs"
  , "spec"
  , "spec-discovery"
  , "strings"
  , "stringutils"
  , "transformers"
  , "tuples"
  , "url-immutable"
  , "yoga-json"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
}
