name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (e.g. latest, v1.0.0)"
        required: true
        default: "latest"

jobs:
  publish:
    name: Build and Push
    uses: benkio/minsi/.github/workflows/publish-docker-image.yml@main
    with:
      source: build
      tag: ${{ inputs.tag }}
      image: benkio/minsi
    secrets: inherit
